/**
 * SocialShareModal — "Del på Social" modal for articles and recipes.
 * Opens from AdminBlog / AdminRecipes with pre-filled content.
 * Generates AI captions per platform, uses featured image, supports scheduling.
 */
import { useState, useEffect, useCallback } from 'react'
import {
  X, Share2, Send, Clock, Loader2, RefreshCw, Instagram, Youtube, Facebook,
  Upload, CheckCircle, XCircle, AlertTriangle, Calendar
} from 'lucide-react'
import {
  getConnectedAccounts, createPost, publishNow, uploadMedia,
  generateSocialCaption, generateAllCaptions, validatePostForPlatforms,
  PLATFORM_INFO,
  type ConnectedAccount, type Platform, type MediaType
} from '@/lib/socialPublisher'

// TikTok icon
function TikTokIcon({ className }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" className={className}>
      <path d="M19.59 6.69a4.83 4.83 0 01-3.77-4.25V2h-3.45v13.67a2.89 2.89 0 01-2.88 2.5 2.89 2.89 0 01-2.89-2.89 2.89 2.89 0 012.89-2.89c.28 0 .54.04.79.1V9.01a6.27 6.27 0 00-.79-.05 6.34 6.34 0 00-6.34 6.34 6.34 6.34 0 006.34 6.34 6.34 6.34 0 006.34-6.34V9.48a8.2 8.2 0 004.76 1.52V7.56a4.84 4.84 0 01-1-.87z" />
    </svg>
  )
}

const PLATFORM_ICONS: Record<Platform, React.ReactNode> = {
  instagram: <Instagram className="h-4 w-4" />,
  facebook: <Facebook className="h-4 w-4" />,
  youtube: <Youtube className="h-4 w-4" />,
  tiktok: <TikTokIcon className="h-4 w-4" />,
}

export interface SocialShareData {
  contentType: 'article' | 'recipe'
  title: string               // In current language
  summary: string             // In current language
  categories: string[]
  tags: string[]
  featuredImageUrl?: string    // Featured image URL
  articleId?: string           // UUID to link in social_publish_queue
  url?: string                 // Published URL for link sharing
  lang: string                 // 'da' | 'en' | 'se'
  nutritionInfo?: string       // For recipes: "320 kcal, 5g netto carbs"
}

interface Props {
  isOpen: boolean
  onClose: () => void
  data: SocialShareData
}

export default function SocialShareModal({ isOpen, onClose, data }: Props) {
  // Accounts
  const [accounts, setAccounts] = useState<ConnectedAccount[]>([])
  const [loadingAccounts, setLoadingAccounts] = useState(true)

  // Selected platforms
  const [selectedPlatforms, setSelectedPlatforms] = useState<Platform[]>([])

  // Per-platform captions (generated by AI, editable)
  const [captions, setCaptions] = useState<Partial<Record<Platform, string>>>({})
  const [activeTab, setActiveTab] = useState<Platform | null>(null)

  // Media
  const [mediaUrls, setMediaUrls] = useState<string[]>([])
  const [mediaType, setMediaType] = useState<MediaType>('image')
  const [uploadingMedia, setUploadingMedia] = useState(false)

  // Schedule
  const [scheduleDate, setScheduleDate] = useState('')

  // AI generation state
  const [generatingCaptions, setGeneratingCaptions] = useState(false)
  const [generatingPlatform, setGeneratingPlatform] = useState<Platform | null>(null)

  // Publishing
  const [publishing, setPublishing] = useState(false)
  const [saving, setSaving] = useState(false)

  // Feedback
  const [feedback, setFeedback] = useState<{ type: 'success' | 'error'; message: string } | null>(null)

  // Load accounts on mount
  useEffect(() => {
    if (isOpen) {
      loadAccounts()
      // Pre-fill featured image
      if (data.featuredImageUrl) {
        setMediaUrls([data.featuredImageUrl])
        setMediaType('image')
      }
    }
  }, [isOpen]) // eslint-disable-line react-hooks/exhaustive-deps

  // Reset when closed
  useEffect(() => {
    if (!isOpen) {
      setSelectedPlatforms([])
      setCaptions({})
      setActiveTab(null)
      setMediaUrls([])
      setScheduleDate('')
      setFeedback(null)
    }
  }, [isOpen])

  const loadAccounts = useCallback(async () => {
    setLoadingAccounts(true)
    try {
      const data = await getConnectedAccounts()
      setAccounts(data)
    } catch (err) {
      console.error('Failed to load accounts:', err)
    } finally {
      setLoadingAccounts(false)
    }
  }, [])

  const connectedPlatforms = [...new Set(accounts.map(a => a.platform))]

  // ── Toggle platform & auto-generate caption ──────────

  async function togglePlatform(platform: Platform) {
    const isSelected = selectedPlatforms.includes(platform)

    if (isSelected) {
      setSelectedPlatforms(prev => prev.filter(p => p !== platform))
      if (activeTab === platform) {
        const remaining = selectedPlatforms.filter(p => p !== platform)
        setActiveTab(remaining[0] || null)
      }
    } else {
      setSelectedPlatforms(prev => [...prev, platform])
      setActiveTab(platform)

      // Auto-generate caption if not already generated
      if (!captions[platform]) {
        setGeneratingPlatform(platform)
        try {
          const caption = await generateSocialCaption({
            platform,
            contentType: data.contentType,
            title: data.title,
            summary: data.summary,
            categories: data.categories,
            tags: data.tags,
            lang: data.lang,
            url: data.url,
            nutritionInfo: data.nutritionInfo,
          })
          setCaptions(prev => ({ ...prev, [platform]: caption }))
        } catch (err) {
          setCaptions(prev => ({ ...prev, [platform]: `[Fejl: ${(err as Error).message}]` }))
        } finally {
          setGeneratingPlatform(null)
        }
      }
    }
  }

  // ── Generate all captions at once ────────────────────

  async function handleGenerateAll() {
    if (selectedPlatforms.length === 0) return
    setGeneratingCaptions(true)
    try {
      const results = await generateAllCaptions(selectedPlatforms, {
        contentType: data.contentType,
        title: data.title,
        summary: data.summary,
        categories: data.categories,
        tags: data.tags,
        lang: data.lang,
        url: data.url,
        nutritionInfo: data.nutritionInfo,
      })
      setCaptions(prev => ({ ...prev, ...results }))
    } catch (err) {
      setFeedback({ type: 'error', message: 'AI-generering fejlede' })
    } finally {
      setGeneratingCaptions(false)
    }
  }

  // ── Regenerate single platform ───────────────────────

  async function handleRegenerate(platform: Platform) {
    setGeneratingPlatform(platform)
    try {
      const caption = await generateSocialCaption({
        platform,
        contentType: data.contentType,
        title: data.title,
        summary: data.summary,
        categories: data.categories,
        tags: data.tags,
        lang: data.lang,
        url: data.url,
        nutritionInfo: data.nutritionInfo,
      })
      setCaptions(prev => ({ ...prev, [platform]: caption }))
    } catch (err) {
      setFeedback({ type: 'error', message: `Regenerering fejlede: ${(err as Error).message}` })
    } finally {
      setGeneratingPlatform(null)
    }
  }

  // ── Media upload ─────────────────────────────────────

  async function handleMediaUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const files = e.target.files
    if (!files?.length) return
    setUploadingMedia(true)
    try {
      for (const file of Array.from(files)) {
        const url = await uploadMedia(file)
        setMediaUrls(prev => [...prev, url])
      }
      if (files[0].type.startsWith('video/')) setMediaType('video')
      else if (mediaUrls.length + files.length > 1) setMediaType('carousel')
    } catch {
      setFeedback({ type: 'error', message: 'Upload fejlede' })
    } finally {
      setUploadingMedia(false)
    }
  }

  function removeMedia(index: number) {
    setMediaUrls(prev => prev.filter((_, i) => i !== index))
  }

  // ── Publish / Save ───────────────────────────────────

  async function handlePublish() {
    if (selectedPlatforms.length === 0) return
    setPublishing(true)
    try {
      // Use the active tab's caption as the primary text (or first platform)
      const primaryCaption = captions[activeTab || selectedPlatforms[0]] || ''

      const post = await createPost({
        content_text: primaryCaption,
        media_urls: mediaUrls.length > 0 ? mediaUrls : undefined,
        media_type: mediaUrls.length > 0 ? mediaType : 'text',
        platforms: selectedPlatforms,
        article_id: data.articleId,
        tags: data.tags,
      })

      const result = await publishNow(post.id)
      if (result.success) {
        setFeedback({ type: 'success', message: 'Publiceret på alle platforme!' })
        setTimeout(onClose, 1500)
      } else {
        setFeedback({ type: 'error', message: 'Delvis fejl — se historik i Social Publisher' })
      }
    } catch (err) {
      setFeedback({ type: 'error', message: `Publicering fejlede: ${(err as Error).message}` })
    } finally {
      setPublishing(false)
    }
  }

  async function handleSaveDraft() {
    setSaving(true)
    try {
      const primaryCaption = captions[activeTab || selectedPlatforms[0]] || ''
      await createPost({
        content_text: primaryCaption,
        media_urls: mediaUrls.length > 0 ? mediaUrls : undefined,
        media_type: mediaUrls.length > 0 ? mediaType : 'text',
        platforms: selectedPlatforms,
        scheduled_at: scheduleDate || null,
        article_id: data.articleId,
        tags: data.tags,
      })
      setFeedback({ type: 'success', message: scheduleDate ? 'Post planlagt!' : 'Kladde gemt!' })
      setTimeout(onClose, 1500)
    } catch {
      setFeedback({ type: 'error', message: 'Kunne ikke gemme' })
    } finally {
      setSaving(false)
    }
  }

  // ── Validation ───────────────────────────────────────

  const currentCaption = captions[activeTab || selectedPlatforms[0]] || ''
  const validationErrors = selectedPlatforms.length > 0
    ? validatePostForPlatforms(selectedPlatforms, currentCaption, mediaUrls, mediaType)
    : []
  const hasBlockingErrors = validationErrors.some(e => e.severity === 'error')

  // ── Auto-clear feedback ──────────────────────────────

  useEffect(() => {
    if (feedback) {
      const timer = setTimeout(() => setFeedback(null), 4000)
      return () => clearTimeout(timer)
    }
  }, [feedback])

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />

      {/* Modal */}
      <div className="relative w-full max-w-3xl max-h-[90vh] overflow-y-auto rounded-xl border border-border bg-background shadow-2xl">
        {/* Header */}
        <div className="sticky top-0 z-10 flex items-center justify-between p-4 border-b border-border bg-background/95 backdrop-blur-sm rounded-t-xl">
          <div className="flex items-center gap-2">
            <Share2 className="h-5 w-5 text-accent" />
            <div>
              <h2 className="font-serif font-bold text-lg">Del på Social</h2>
              <p className="text-xs text-muted-foreground truncate max-w-md">
                {data.contentType === 'recipe' ? 'Opskrift' : 'Artikel'}: {data.title}
              </p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 rounded-lg hover:bg-muted/50 transition-colors">
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="p-4 space-y-5">
          {/* Feedback */}
          {feedback && (
            <div className={`p-3 rounded-lg text-sm flex items-center gap-2 ${
              feedback.type === 'success'
                ? 'bg-green-500/10 text-green-700 border border-green-500/20'
                : 'bg-red-500/10 text-red-700 border border-red-500/20'
            }`}>
              {feedback.type === 'success' ? <CheckCircle className="h-4 w-4" /> : <XCircle className="h-4 w-4" />}
              {feedback.message}
            </div>
          )}

          {/* Platform selector */}
          <div>
            <label className="text-sm font-medium mb-2 block">Vælg platforme</label>
            {loadingAccounts ? (
              <div className="flex items-center gap-2 text-sm text-muted-foreground">
                <Loader2 className="h-4 w-4 animate-spin" /> Henter konti...
              </div>
            ) : (
              <div className="flex flex-wrap gap-2">
                {(Object.keys(PLATFORM_INFO) as Platform[]).map(p => {
                  const connected = connectedPlatforms.includes(p)
                  const selected = selectedPlatforms.includes(p)
                  const generating = generatingPlatform === p
                  return (
                    <button
                      key={p}
                      onClick={() => connected && togglePlatform(p)}
                      disabled={!connected || generatingCaptions}
                      className={`flex items-center gap-2 px-3 py-2 rounded-lg text-sm border transition-all ${
                        selected
                          ? 'border-accent bg-accent/10 text-accent'
                          : connected
                          ? 'border-border hover:border-accent/50'
                          : 'border-border/50 opacity-40 cursor-not-allowed'
                      }`}
                    >
                      {generating ? (
                        <Loader2 className="h-4 w-4 animate-spin" />
                      ) : (
                        <span style={{ color: selected ? PLATFORM_INFO[p].color : undefined }}>
                          {PLATFORM_ICONS[p]}
                        </span>
                      )}
                      {PLATFORM_INFO[p].name}
                      {!connected && <span className="text-xs opacity-60">(ikke tilsluttet)</span>}
                    </button>
                  )
                })}
              </div>
            )}
            {connectedPlatforms.length === 0 && !loadingAccounts && (
              <p className="text-xs text-muted-foreground mt-2">
                Ingen konti tilsluttet. Gå til <a href="/admin/social-publisher?tab=accounts" className="text-accent hover:underline">Social Publisher → Konti</a> for at tilslutte.
              </p>
            )}
          </div>

          {/* Per-platform caption tabs + editor */}
          {selectedPlatforms.length > 0 && (
            <div>
              {/* Tab bar */}
              <div className="flex items-center gap-1 border-b border-border mb-3">
                {selectedPlatforms.map(p => (
                  <button
                    key={p}
                    onClick={() => setActiveTab(p)}
                    className={`flex items-center gap-1.5 px-3 py-2 text-sm border-b-2 transition-colors ${
                      activeTab === p
                        ? 'border-accent text-accent'
                        : 'border-transparent text-muted-foreground hover:text-foreground'
                    }`}
                  >
                    <span style={{ color: PLATFORM_INFO[p].color }}>{PLATFORM_ICONS[p]}</span>
                    {PLATFORM_INFO[p].name}
                  </button>
                ))}
                <div className="flex-1" />
                <button
                  onClick={handleGenerateAll}
                  disabled={generatingCaptions}
                  className="flex items-center gap-1 px-2 py-1 text-xs text-accent hover:underline disabled:opacity-40"
                  title="Regenerer alle captions"
                >
                  {generatingCaptions ? <Loader2 className="h-3 w-3 animate-spin" /> : <RefreshCw className="h-3 w-3" />}
                  Regenerer alle
                </button>
              </div>

              {/* Active platform editor */}
              {activeTab && (
                <div>
                  <div className="relative">
                    <textarea
                      value={captions[activeTab] || ''}
                      onChange={e => setCaptions(prev => ({ ...prev, [activeTab]: e.target.value }))}
                      placeholder={generatingPlatform === activeTab ? 'AI genererer caption...' : 'Caption tekst...'}
                      disabled={generatingPlatform === activeTab}
                      className="w-full h-36 p-3 rounded-lg border border-border bg-background text-foreground resize-none focus:outline-none focus:ring-2 focus:ring-accent/50 text-sm disabled:opacity-50"
                    />
                    {generatingPlatform === activeTab && (
                      <div className="absolute inset-0 flex items-center justify-center bg-background/80 rounded-lg">
                        <div className="flex items-center gap-2 text-sm text-accent">
                          <Loader2 className="h-5 w-5 animate-spin" />
                          AI genererer {PLATFORM_INFO[activeTab].name} caption...
                        </div>
                      </div>
                    )}
                  </div>

                  <div className="flex items-center justify-between mt-1">
                    <span className={`text-xs ${
                      (captions[activeTab]?.length || 0) > PLATFORM_INFO[activeTab].maxChars
                        ? 'text-red-500'
                        : 'text-muted-foreground'
                    }`}>
                      {captions[activeTab]?.length || 0} / {PLATFORM_INFO[activeTab].maxChars} tegn
                    </span>
                    <button
                      onClick={() => handleRegenerate(activeTab)}
                      disabled={generatingPlatform === activeTab}
                      className="flex items-center gap-1 text-xs text-accent hover:underline disabled:opacity-40"
                    >
                      <RefreshCw className="h-3 w-3" />
                      Regenerer
                    </button>
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Media section */}
          <div>
            <label className="text-sm font-medium mb-2 block">Medier</label>
            <div className="flex flex-wrap gap-3">
              {mediaUrls.map((url, i) => (
                <div key={i} className="relative group w-20 h-20 rounded-lg overflow-hidden border border-border">
                  <img src={url} alt="" className="w-full h-full object-cover" />
                  <button
                    onClick={() => removeMedia(i)}
                    className="absolute top-1 right-1 p-0.5 rounded-full bg-black/60 text-white opacity-0 group-hover:opacity-100 transition-opacity"
                  >
                    <X className="h-3 w-3" />
                  </button>
                  {i === 0 && data.featuredImageUrl && url === data.featuredImageUrl && (
                    <span className="absolute bottom-0 left-0 right-0 bg-black/60 text-white text-[10px] text-center py-0.5">
                      Featured
                    </span>
                  )}
                </div>
              ))}
              <label className="w-20 h-20 rounded-lg border-2 border-dashed border-border hover:border-accent/50 flex flex-col items-center justify-center cursor-pointer transition-colors">
                {uploadingMedia ? (
                  <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
                ) : (
                  <>
                    <Upload className="h-5 w-5 text-muted-foreground" />
                    <span className="text-[10px] text-muted-foreground mt-0.5">Upload</span>
                  </>
                )}
                <input
                  type="file"
                  accept="image/*,video/*"
                  multiple
                  onChange={handleMediaUpload}
                  className="hidden"
                  disabled={uploadingMedia}
                />
              </label>
            </div>
          </div>

          {/* Schedule */}
          <div>
            <label className="text-sm font-medium mb-2 flex items-center gap-1">
              <Calendar className="h-4 w-4" /> Planlæg (valgfrit)
            </label>
            <input
              type="datetime-local"
              value={scheduleDate}
              onChange={e => setScheduleDate(e.target.value)}
              className="w-full p-2.5 rounded-lg border border-border bg-background text-foreground text-sm focus:outline-none focus:ring-2 focus:ring-accent/50"
            />
          </div>

          {/* Validation */}
          {validationErrors.length > 0 && (
            <div className="space-y-1">
              {validationErrors.map((err, i) => (
                <div key={i} className={`flex items-start gap-2 text-xs p-2 rounded-lg ${
                  err.severity === 'error'
                    ? 'bg-red-500/10 text-red-700 border border-red-500/20'
                    : 'bg-amber-500/10 text-amber-700 border border-amber-500/20'
                }`}>
                  {err.severity === 'error' ? <XCircle className="h-3.5 w-3.5 mt-0.5 shrink-0" /> : <AlertTriangle className="h-3.5 w-3.5 mt-0.5 shrink-0" />}
                  <span><strong>{PLATFORM_INFO[err.platform].name}:</strong> {err.message}</span>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Footer actions */}
        <div className="sticky bottom-0 flex items-center justify-end gap-3 p-4 border-t border-border bg-background/95 backdrop-blur-sm rounded-b-xl">
          <button
            onClick={onClose}
            className="px-4 py-2 rounded-lg border border-border text-sm hover:bg-muted/50 transition-colors"
          >
            Annuller
          </button>
          <button
            onClick={handleSaveDraft}
            disabled={saving || selectedPlatforms.length === 0}
            className="flex items-center gap-2 px-4 py-2 rounded-lg border border-border text-sm hover:bg-muted/50 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
          >
            {saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Clock className="h-4 w-4" />}
            {scheduleDate ? 'Planlæg' : 'Gem kladde'}
          </button>
          <button
            onClick={handlePublish}
            disabled={publishing || hasBlockingErrors || selectedPlatforms.length === 0 || !currentCaption.trim()}
            className="flex items-center gap-2 px-5 py-2 rounded-lg bg-accent text-accent-foreground font-medium text-sm hover:bg-accent/90 disabled:opacity-40 disabled:cursor-not-allowed transition-colors"
          >
            {publishing ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
            Publicer nu
          </button>
        </div>
      </div>
    </div>
  )
}
